### PR TITLE
Add disqus support

### PR DESCRIPTION
**Pull request by ripienaar**
This allows people to enable disqus on pages based on setting setting a disqus shortname in the _config.yaml and then on a per page basis setting ```disqus: 1```

### CODE REVIEW

**Comment by ripienaar** [comment]
You can see it in action @ http://ripienaar.github.io/travlrmap/ref/config-sets-section.html

**Comment by bruth** [comment]
This is nice. Thanks!

**Comment by ripienaar** [comment]
Great, love this little tool, I might upgrade bootstrap to latest as well, if this is something you'd be interested in?

**Comment by bruth** [comment]
Thank you. For sure, that is definitely welcome.

**Comment by ripienaar** [comment]
sweet, thanks

**Pull request merged**
